version: "3"
services:
  web:
    build: ./perl
    volumes:
      - ./perl:/usr/local/src/
    links:
      - mysql
      - redis
    ports:
      - "5000:5000"
    environment:
      - TEST_REDIS=redis
      - TEST_DB_URL=dbi:mysql:database=infratest;host=mysql;port=3306
    command: "carton exec plackup -r -p 5000 api.psgi"
  queue:
    build: ./perl
    volumes:
      - ./perl:/usr/local/src/
    links:
      - mysql
      - redis
    environment:
      - TEST_REDIS=redis
      - TEST_DB_URL=dbi:mysql:database=infratest;host=mysql;port=3306
    command: "carton exec perl queue.pl"
  redis:
    build: ./redis
    ports:
      - "6379:6379"
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
